name: Pipeline VictoriaCinemaBot

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: Install dependencies
      run: pip install -r src/requirements.txt
    
    - name: Run Test on Python code with flake8
      run: flake8 --ignore=E501,E121,E126,E302,E305,W291 .
    
    - name: Run Pytest
      working-directory: src/
      run: pytest
      
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: USERNAME DOCKER
          password: PASSWORD DOCKER
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: maxbubblegum/victoriacinemabot:latest

